"""
WitnessChain — Report Generator
Generates structured case documentation in PDF and DOCX formats.
"""

import io
import json
import os
from datetime import datetime, timezone
from typing import Optional

from fpdf import FPDF
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


class ReportGenerator:
    """
    Generates structured human rights case reports from extracted
    testimony data and cross-reference analysis.

    Report sections:
    1. Executive Summary
    2. Incident Timeline
    3. Corroborated Facts
    4. Discrepancies
    5. Evidence Inventory
    6. Recommended Actions
    7. Data Provenance
    """

    # Helper: resolve font style safely.
    # NotoSans is registered as regular only — bold/italic variants are not
    # available.  Helvetica (built-in) supports "B" and "I" natively.
    @staticmethod
    def _font_style(font_name: str, desired: str) -> str:
        """Return *desired* style for built-in fonts, '' for NotoSans."""
        if font_name == "NotoSans":
            return ""
        return desired

    def generate_pdf(self, extracted_data: list, crossref_data: dict) -> bytes:
        """
        Generate a PDF case report with Unicode support for multilingual testimonies.
        """
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)

        # --- Multilingual Font Registration ---
        # NotoSans-Regular.ttf is bundled at data/fonts/ — no network calls.
        # Falls back to Helvetica if the file is missing.
        font_name = "Helvetica"
        font_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "fonts")
        noto_path = os.path.join(font_dir, "NotoSans-Regular.ttf")

        if os.path.exists(noto_path):
            try:
                pdf.add_font("NotoSans", "", noto_path)
                font_name = "NotoSans"
                print(f"[WitnessChain] Unicode font registered: {font_name}")
            except Exception as e:
                print(f"[WitnessChain] Warning: Could not register Unicode font: {e}")

        # --- Title Page ---
        pdf.add_page()
        pdf.set_font(font_name, self._font_style(font_name, "B"), 24)
        pdf.cell(0, 20, "WitnessChain Case Report", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.set_font(font_name, "", 12)
        pdf.cell(0, 10, f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.cell(0, 10, f"Testimonies Analysed: {len(extracted_data)}", new_x="LMARGIN", new_y="NEXT", align="C")

        # Disclaimer
        pdf.ln(10)
        pdf.set_font(font_name, self._font_style(font_name, "I"), 9)
        pdf.multi_cell(0, 5, (
            "DISCLAIMER: This report was generated by WitnessChain, a research prototype. "
            "All extracted data requires independent verification by qualified human rights "
            "investigators before use in legal proceedings."
        ))
        pdf.ln(10)

        # --- Section 1: Executive Summary ---
        self._pdf_section_header(pdf, "1. Executive Summary")
        testimony_count = len(extracted_data)
        incident_types = set()
        locations = set()
        for d in extracted_data:
            if d.get("incident_type"):
                incident_types.add(d["incident_type"])
            if d.get("incident_location"):
                locations.add(d["incident_location"])

        summary = (
            f"This report synthesises {testimony_count} testimonies. "
            f"Incident types documented: {', '.join(incident_types) or 'N/A'}. "
            f"Locations referenced: {', '.join(locations) or 'N/A'}."
        )
        pdf.set_font(font_name, "", 10)
        pdf.multi_cell(0, 6, summary)
        pdf.ln(5)

        # --- Section 2: Incident Timeline ---
        self._pdf_section_header(pdf, "2. Incident Timeline")
        timeline = crossref_data.get("timeline", [])
        if timeline:
            for event in timeline:
                pdf.set_font(font_name, self._font_style(font_name, "B"), 10)
                pdf.cell(0, 6, f"  {event.get('date_or_period', 'Unknown date')}", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font(font_name, "", 10)
                pdf.multi_cell(0, 6, f"    {event.get('event_description', 'No description')}")
                ids = event.get("testimony_ids", [])
                pdf.set_font(font_name, self._font_style(font_name, "I"), 9)
                pdf.cell(0, 5, f"    Sources: {', '.join(ids)}", new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)
        else:
            pdf.set_font(font_name, "", 10)
            pdf.cell(0, 6, "  No timeline data available.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # --- Section 3: Corroborated Facts ---
        self._pdf_section_header(pdf, "3. Corroborated Facts")
        corroborated = crossref_data.get("corroborated_facts", [])
        if corroborated:
            for i, fact in enumerate(corroborated, 1):
                pdf.set_font(font_name, self._font_style(font_name, "B"), 10)
                confidence = fact.get("confidence", "unknown")
                pdf.cell(0, 6, f"  {i}. [{confidence.upper()}] {fact.get('fact', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
                ids = fact.get("testimony_ids", [])
                pdf.set_font(font_name, self._font_style(font_name, "I"), 9)
                pdf.cell(0, 5, f"     Corroborated by: {', '.join(ids)}", new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)
        else:
            pdf.set_font(font_name, "", 10)
            pdf.cell(0, 6, "  No corroborated facts identified.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # --- Section 4: Discrepancies ---
        self._pdf_section_header(pdf, "4. Discrepancies")
        discrepancies = crossref_data.get("discrepancies", [])
        if discrepancies:
            for i, disc in enumerate(discrepancies, 1):
                pdf.set_font(font_name, "", 10)
                pdf.multi_cell(0, 6, f"  {i}. {disc.get('description', 'N/A')}")
                ids = disc.get("testimony_ids", [])
                pdf.set_font(font_name, self._font_style(font_name, "I"), 9)
                pdf.cell(0, 5, f"     Between: {', '.join(ids)}", new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)
        else:
            pdf.set_font(font_name, "", 10)
            pdf.cell(0, 6, "  No discrepancies identified.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # --- Section 5: Evidence Inventory ---
        self._pdf_section_header(pdf, "5. Evidence Inventory")
        all_evidence = []
        for d in extracted_data:
            evidence = d.get("evidence_mentioned", [])
            if evidence:
                tid = d.get("testimony_id", "unknown")
                for e in evidence:
                    all_evidence.append(f"{e} (source: {tid})")

        if all_evidence:
            for item in all_evidence:
                pdf.set_font(font_name, "", 10)
                pdf.cell(0, 6, f"  - {item}", new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.set_font(font_name, "", 10)
            pdf.cell(0, 6, "  No physical evidence documented.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # --- Section 6: Evidence Gaps ---
        self._pdf_section_header(pdf, "6. Evidence Gaps & Recommended Actions")
        gaps = crossref_data.get("evidence_gaps", [])
        if gaps:
            for gap in gaps:
                pdf.set_font(font_name, "", 10)
                pdf.cell(0, 6, f"  - {gap}", new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.set_font(font_name, "", 10)
            pdf.cell(0, 6, "  No evidence gaps identified.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # --- Section 7: Data Provenance ---
        self._pdf_section_header(pdf, "7. Data Provenance")
        pdf.set_font(font_name, "", 10)
        pdf.multi_cell(0, 6, (
            f"Report generated by WitnessChain v1.0\n"
            f"Model: Gemma 4 (quantised, local inference only)\n"
            f"Testimonies processed: {testimony_count}\n"
            f"All inference performed locally — no data transmitted to external APIs.\n"
            f"Extraction prompts are public and version-controlled in the prompts/ directory.\n"
        ))

        token_usage = crossref_data.get("token_usage", {})
        if token_usage:
            pdf.set_font(font_name, self._font_style(font_name, "I"), 9)
            pdf.cell(0, 5, f"Context window usage: {token_usage.get('display', 'N/A')}", new_x="LMARGIN", new_y="NEXT")

        # Output PDF bytes
        return pdf.output()

    def generate_docx(self, extracted_data: list, crossref_data: dict) -> bytes:
        """
        Generate a DOCX case report.

        Args:
            extracted_data: List of extracted entity dicts from ExtractionEngine.
            crossref_data: Cross-reference analysis dict from CrossReferenceEngine.

        Returns:
            DOCX file as bytes.
        """
        doc = Document()

        # --- Title ---
        title = doc.add_heading("WitnessChain Case Report", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph(
            f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  |  "
            f"Testimonies Analysed: {len(extracted_data)}"
        ).alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Disclaimer
        disclaimer = doc.add_paragraph()
        run = disclaimer.add_run(
            "DISCLAIMER: This report was generated by WitnessChain, a research prototype. "
            "All extracted data requires independent verification by qualified human rights "
            "investigators before use in legal proceedings."
        )
        run.font.size = Pt(9)
        run.font.italic = True

        # --- Section 1: Executive Summary ---
        doc.add_heading("1. Executive Summary", level=1)
        testimony_count = len(extracted_data)
        incident_types = set()
        locations = set()
        for d in extracted_data:
            if d.get("incident_type"):
                incident_types.add(d["incident_type"])
            if d.get("incident_location"):
                locations.add(d["incident_location"])

        doc.add_paragraph(
            f"This report synthesises {testimony_count} testimonies. "
            f"Incident types documented: {', '.join(incident_types) or 'N/A'}. "
            f"Locations referenced: {', '.join(locations) or 'N/A'}."
        )

        # --- Section 2: Incident Timeline ---
        doc.add_heading("2. Incident Timeline", level=1)
        timeline = crossref_data.get("timeline", [])
        if timeline:
            for event in timeline:
                p = doc.add_paragraph()
                run = p.add_run(f"{event.get('date_or_period', 'Unknown date')}: ")
                run.bold = True
                p.add_run(event.get("event_description", "No description"))
                ids = event.get("testimony_ids", [])
                source_p = doc.add_paragraph(f"Sources: {', '.join(ids)}")
                source_p.runs[0].font.italic = True
                source_p.runs[0].font.size = Pt(9)
        else:
            doc.add_paragraph("No timeline data available.")

        # --- Section 3: Corroborated Facts ---
        doc.add_heading("3. Corroborated Facts", level=1)
        corroborated = crossref_data.get("corroborated_facts", [])
        if corroborated:
            for i, fact in enumerate(corroborated, 1):
                confidence = fact.get("confidence", "unknown")
                p = doc.add_paragraph(f"{i}. [{confidence.upper()}] {fact.get('fact', 'N/A')}")
                p.runs[0].bold = True
                ids = fact.get("testimony_ids", [])
                source_p = doc.add_paragraph(f"Corroborated by: {', '.join(ids)}")
                source_p.runs[0].font.italic = True
                source_p.runs[0].font.size = Pt(9)
        else:
            doc.add_paragraph("No corroborated facts identified.")

        # --- Section 4: Discrepancies ---
        doc.add_heading("4. Discrepancies", level=1)
        discrepancies = crossref_data.get("discrepancies", [])
        if discrepancies:
            for i, disc in enumerate(discrepancies, 1):
                doc.add_paragraph(f"{i}. {disc.get('description', 'N/A')}")
                ids = disc.get("testimony_ids", [])
                source_p = doc.add_paragraph(f"Between: {', '.join(ids)}")
                source_p.runs[0].font.italic = True
        else:
            doc.add_paragraph("No discrepancies identified.")

        # --- Section 5: Evidence Inventory ---
        doc.add_heading("5. Evidence Inventory", level=1)
        all_evidence = []
        for d in extracted_data:
            evidence = d.get("evidence_mentioned", [])
            if evidence:
                tid = d.get("testimony_id", "unknown")
                for e in evidence:
                    all_evidence.append(f"{e} (source: {tid})")

        if all_evidence:
            for item in all_evidence:
                doc.add_paragraph(item, style="List Bullet")
        else:
            doc.add_paragraph("No physical evidence documented.")

        # --- Section 6: Evidence Gaps ---
        doc.add_heading("6. Evidence Gaps & Recommended Actions", level=1)
        gaps = crossref_data.get("evidence_gaps", [])
        if gaps:
            for gap in gaps:
                doc.add_paragraph(gap, style="List Bullet")
        else:
            doc.add_paragraph("No evidence gaps identified.")

        # --- Section 7: Data Provenance ---
        doc.add_heading("7. Data Provenance", level=1)
        doc.add_paragraph(
            f"Report generated by WitnessChain v1.0\n"
            f"Model: Gemma 4 (quantised, local inference only)\n"
            f"Testimonies processed: {testimony_count}\n"
            f"All inference performed locally — no data transmitted to external APIs.\n"
            f"Extraction prompts are public and version-controlled in the prompts/ directory."
        )

        token_usage = crossref_data.get("token_usage", {})
        if token_usage:
            p = doc.add_paragraph(f"Context window usage: {token_usage.get('display', 'N/A')}")
            p.runs[0].font.italic = True
            p.runs[0].font.size = Pt(9)

        # Output DOCX bytes
        buffer = io.BytesIO()
        doc.save(buffer)
        return buffer.getvalue()

    def _pdf_section_header(self, pdf: FPDF, title: str):
        """Add a styled section header to the PDF."""
        # Detect if we successfully loaded a Unicode font
        current_font = pdf.font_family
        pdf.set_font(current_font, self._font_style(current_font, "B"), 14)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 10, f"  {title}", new_x="LMARGIN", new_y="NEXT", fill=True)
        pdf.ln(3)
